import sys
import os

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)
from backend.embeddings.embedder import get_embedding

import faiss
import numpy as np

# Dimension of embeddings generated by the model
DIMENSION = 384

# Create FAISS index
index = faiss.IndexFlatL2(DIMENSION)

# Store text corresponding to vectors
stored_texts = []


def add_vectors(embeddings, texts):
    """
    Add embeddings and corresponding text to FAISS database
    """
    vectors = np.array(embeddings).astype("float32")
    index.add(vectors)
    stored_texts.extend(texts)


def search_vectors(query_embedding, top_k=5):
    """
    Perform similarity search in FAISS database
    """
    query_vector = np.array([query_embedding]).astype("float32")
    distances, indices = index.search(query_vector, top_k)

    results = []
    for idx in indices[0]:
        if idx < len(stored_texts):
            results.append(stored_texts[idx])

    return results


if __name__ == "__main__":
    from backend.embeddings.embedder import get_embedding


    texts = [
        "BERT converts text into vectors",
        "FAISS is used for similarity search",
        "Embeddings capture semantic meaning"
    ]

    embeddings = [get_embedding(t) for t in texts]
    add_vectors(embeddings, texts)

    query = "how is text converted into numbers"
    results = search_vectors(get_embedding(query))

    print("Search Results:")
    for r in results:
        print("-", r)
