import faiss
import numpy as np

# Dimension of embedding generated by model
DIMENSION = 384

# Create FAISS index
index = faiss.IndexFlatL2(DIMENSION)

# Store original text corresponding to vectors
stored_texts = []

def add_vectors(embeddings, texts):
    """
    Add vectors and corresponding text into FAISS database
    """
    vectors = np.array(embeddings).astype("float32")
    index.add(vectors)
    stored_texts.extend(texts)

def search_vectors(query_embedding, top_k=5):
    """
    Perform similarity search in vector database
    """
    query_vector = np.array([query_embedding]).astype("float32")
    distances, indices = index.search(query_vector, top_k)

    results = []
    for idx in indices[0]:
        if idx < len(stored_texts):
            results.append(stored_texts[idx])

    return results
# FAISS vector database module
